### ISSUE TITLE
Any reference papers?

### ISSUE THREAD

**Issue by xuguozhi** [nmfisher/pytorch_blendshape_prediction#1]
Hi， how is your input data?(RGB/audio) what is your idea

**Comment by nmfisher** [comment]
This is very similar to https://arxiv.org/abs/1905.11142, so predicting raw blendshapes (e.g. recorded mocap from Apple ARKit) from audio.

It sounds like you might be thinking of predicting blendshapes from image data (e.g. image-only facial video capture), which this doesn't do.

**Comment by xuguozhi** [comment]
wow, I think predicting blendshape from audio is difficult. nvidia omniverse has the same tools. https://www.nvidia.cn/omniverse/apps/audio2face/
